use std::fmt::Write;

use crate::ir::{EffectSpec, RuleSetIr, ValueSpec};

pub fn generate_module(ir: &RuleSetIr) -> String {
    let mut out = String::new();

    writeln!(&mut out, "// @generated by herdingcats_codegen").unwrap();
    writeln!(&mut out, "#[allow(dead_code)]").unwrap();
    writeln!(&mut out, "pub mod generated_rules {{").unwrap();
    writeln!(&mut out, "    #[derive(Clone, Debug, PartialEq)]").unwrap();
    writeln!(&mut out, "    pub enum GeneratedOp {{").unwrap();
    for rule in &ir.rules {
        for effect in &rule.effects {
            if let EffectSpec::Emit(emit) = effect {
                write!(&mut out, "        {} {{", emit.operation).unwrap();
                for (idx, arg) in emit.args.iter().enumerate() {
                    if idx > 0 {
                        write!(&mut out, ", ").unwrap();
                    }
                    write!(&mut out, "{}: {}", arg.name, rust_type_for_value(&arg.value)).unwrap();
                }
                writeln!(&mut out, " }},").unwrap();
            }
        }
    }
    writeln!(&mut out, "    }}").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "    pub struct GeneratedRuleDescriptor {{").unwrap();
    writeln!(&mut out, "        pub id: &'static str,").unwrap();
    writeln!(&mut out, "        pub priority: u32,").unwrap();
    writeln!(&mut out, "        pub event: &'static str,").unwrap();
    writeln!(&mut out, "        pub effect_count: usize,").unwrap();
    writeln!(&mut out, "    }}").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "    pub static GENERATED_RULES: &[GeneratedRuleDescriptor] = &["
    )
    .unwrap();
    for rule in &ir.rules {
        writeln!(
            &mut out,
            "        GeneratedRuleDescriptor {{ id: {:?}, priority: {}, event: {:?}, effect_count: {} }},",
            rule.id,
            rule.priority,
            rule.event.variant,
            rule.effects.len()
        )
        .unwrap();
    }
    writeln!(&mut out, "    ];").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "    pub fn register_generated_rules<R>(mut register: R)\n    where\n        R: FnMut(&'static str, u32),\n    {{"
    )
    .unwrap();
    writeln!(&mut out, "        for rule in GENERATED_RULES {{").unwrap();
    writeln!(&mut out, "            register(rule.id, rule.priority);").unwrap();
    writeln!(&mut out, "        }}").unwrap();
    writeln!(&mut out, "    }}").unwrap();
    writeln!(&mut out, "}}").unwrap();

    out
}

fn rust_type_for_value(value: &ValueSpec) -> &'static str {
    match value {
        ValueSpec::Binding(_) | ValueSpec::String(_) => "String",
        ValueSpec::Integer(_) => "i64",
        ValueSpec::Boolean(_) => "bool",
    }
}
